defaults:
  vocabulary_path: "${PROJECT_ROOT}/Vocabulary/ORBvoc.txt"
  yaml_path: "${PROJECT_ROOT}/Examples/RGB-D/TUM3.yaml"
  run_parameters:
    repetitions: 1
    save_log: true
    save_camera_trajectory: true
    save_keyframe_trajectory: true

sequences:

  fr3_sitting_static:
    dataset_path: "/home/djn/datasets/TUMRGBD/rgbd_dataset_freiburg3_sitting_static"
    association_path: "/home/djn/datasets/TUMRGBD/rgbd_dataset_freiburg3_sitting_static/associations.txt"
    yaml_path: "${PROJECT_ROOT}/Examples/RGB-D/TUM3.yaml"
    run_parameters: "default"

  fr3_walking_xyz:
    dataset_path: "/home/djn/datasets/TUMRGBD/rgbd_dataset_freiburg3_walking_xyz"
    association_path: "/home/djn/datasets/TUMRGBD/rgbd_dataset_freiburg3_walking_xyz/associations.txt"
    yaml_path: "${PROJECT_ROOT}/Examples/RGB-D/TUM3.yaml"
    run_parameters: "default"

  fr3_walking_rpy:
    dataset_path: "/home/djn/datasets/TUMRGBD/rgbd_dataset_freiburg3_walking_rpy"
    association_path: "/home/djn/datasets/TUMRGBD/rgbd_dataset_freiburg3_walking_rpy/associations.txt"
    yaml_path: "${PROJECT_ROOT}/Examples/RGB-D/TUM3.yaml"
    run_parameters: "default"

  fr3_walking_static:
    dataset_path: "/home/djn/datasets/TUMRGBD/rgbd_dataset_freiburg3_walking_static"
    association_path: "/home/djn/datasets/TUMRGBD/rgbd_dataset_freiburg3_walking_static/associations.txt"
    yaml_path: "${PROJECT_ROOT}/Examples/RGB-D/TUM3.yaml"
    run_parameters: "default"
